-- Sales schema reference
--
-- The authoritative, deployable schema is the ordered migration history in
-- supabase/migrations. The original sale-bound payment schema was created in
-- 20260819131436_development_baseline.sql and is upgraded to the customer
-- receipt/allocation ledger by:
--
--   20260819194218_add_customer_payment_allocations.sql
--   20260819194808_add_safe_sale_customer_reassignment.sql
--
-- Apply the migrations instead of running this reference file directly. The
-- final model contains public.customers, public.sales,
-- public.customer_payments, and public.payment_allocations. Role-aware RLS,
-- creator auditing, validation triggers, the atomic payment RPC, and legacy
-- data conversion are all defined in that migration history.
